### ISSUE TITLE
LICENSE missing

### ISSUE THREAD

**Issue by grische** [raspstephan/weather-benchmark#1]
Hey,
I am interested in using the benchmark, but I wasn't able to find a LICENSE file.
Could you add a LICENSE for this repo?

**Comment by raspstephan** [comment]
The data will be publically available but we have not figured out the details of the license yet. Plus the dataset doesn't exist yet. We hope though that we will have a finished dataset available within two months or so.

**Comment by grische** [comment]
@raspstephan I see. What is the license of the code in this repo though?

**Comment by raspstephan** [comment]
Licence for repository has now been added (MIT)

**Comment by grische** [comment]
90a8758d74b5cc7b88ebf1a45b199fa17ba81be8 🎉

Thank you!
